title: "APSC 453 Science & Authority"
description: "a 400-level capstone course at William & Mary"
url: ""
baseurl: ""
brand_mark: "S&A"
original_site: "https://scienceauthority.wordpress.com"
exported: "Wed, 06 May 2026 00:40:53 +0000"

markdown: kramdown
future: true
permalink: /posts/:slug/

collections:
  materials:
    output: true
    permalink: /pages/:name/

defaults:
  - scope:
      path: ""
      type: materials
    values:
      layout: page
      kind: page
  - scope:
      path: ""
      type: posts
    values:
      layout: page
      kind: post

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  - "wp-content/uploads/**/*.pdf"
  - "wp-content/uploads/**/*.PDF"
